// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package user

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkExistsByEmailStmt, err = db.PrepareContext(ctx, checkExistsByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query CheckExistsByEmail: %w", err)
	}
	if q.checkExistsByNicknameStmt, err = db.PrepareContext(ctx, checkExistsByNickname); err != nil {
		return nil, fmt.Errorf("error preparing query CheckExistsByNickname: %w", err)
	}
	if q.createStmt, err = db.PrepareContext(ctx, create); err != nil {
		return nil, fmt.Errorf("error preparing query Create: %w", err)
	}
	if q.getByEmailStmt, err = db.PrepareContext(ctx, getByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetByEmail: %w", err)
	}
	if q.getByIdStmt, err = db.PrepareContext(ctx, getById); err != nil {
		return nil, fmt.Errorf("error preparing query GetById: %w", err)
	}
	if q.updateProfileByIdStmt, err = db.PrepareContext(ctx, updateProfileById); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProfileById: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkExistsByEmailStmt != nil {
		if cerr := q.checkExistsByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkExistsByEmailStmt: %w", cerr)
		}
	}
	if q.checkExistsByNicknameStmt != nil {
		if cerr := q.checkExistsByNicknameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkExistsByNicknameStmt: %w", cerr)
		}
	}
	if q.createStmt != nil {
		if cerr := q.createStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createStmt: %w", cerr)
		}
	}
	if q.getByEmailStmt != nil {
		if cerr := q.getByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getByEmailStmt: %w", cerr)
		}
	}
	if q.getByIdStmt != nil {
		if cerr := q.getByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getByIdStmt: %w", cerr)
		}
	}
	if q.updateProfileByIdStmt != nil {
		if cerr := q.updateProfileByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProfileByIdStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	checkExistsByEmailStmt    *sql.Stmt
	checkExistsByNicknameStmt *sql.Stmt
	createStmt                *sql.Stmt
	getByEmailStmt            *sql.Stmt
	getByIdStmt               *sql.Stmt
	updateProfileByIdStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		checkExistsByEmailStmt:    q.checkExistsByEmailStmt,
		checkExistsByNicknameStmt: q.checkExistsByNicknameStmt,
		createStmt:                q.createStmt,
		getByEmailStmt:            q.getByEmailStmt,
		getByIdStmt:               q.getByIdStmt,
		updateProfileByIdStmt:     q.updateProfileByIdStmt,
	}
}
