// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package user

import (
	"github.com/google/uuid"
)

type User struct {
	ID         uuid.UUID
	Nickname   string
	Email      string
	Password   string
	ProfileImg string
	CreatedAt  int64
	UpdatedAt  int64
}
