// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: query.sql

package exercise

import (
	"context"

	"github.com/google/uuid"
)

const create = `-- name: Create :exec
INSERT INTO health(id, user_id, exercise_id, weight, ` + "`" + `set` + "`" + `, ` + "`" + `minute` + "`" + `, created_at) VALUES (?,?,?,?,?,?,?)
`

type CreateParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ExerciseID int64
	Weight     int32
	Set        int32
	Minute     int32
	CreatedAt  int64
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.exec(ctx, q.createStmt, create,
		arg.ID,
		arg.UserID,
		arg.ExerciseID,
		arg.Weight,
		arg.Set,
		arg.Minute,
		arg.CreatedAt,
	)
	return err
}

const fetchByDateTime = `-- name: FetchByDateTime :many
SELECT h.id, h.user_id, h.exercise_id, h.weight, h.` + "`" + `set` + "`" + `, h.minute, h.created_at, e.subject FROM health h
         INNER JOIN exercise e on h.exercise_id = e.id
         WHERE h.user_id = ? AND h.created_at BETWEEN ? AND ?
         ORDER BY h.created_at DESC
`

type FetchByDateTimeParams struct {
	UserID      uuid.UUID
	CreatedAt   int64
	CreatedAt_2 int64
}

type FetchByDateTimeRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	ExerciseID int64
	Weight     int32
	Set        int32
	Minute     int32
	CreatedAt  int64
	Subject    string
}

func (q *Queries) FetchByDateTime(ctx context.Context, arg FetchByDateTimeParams) ([]FetchByDateTimeRow, error) {
	rows, err := q.query(ctx, q.fetchByDateTimeStmt, fetchByDateTime, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchByDateTimeRow
	for rows.Next() {
		var i FetchByDateTimeRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExerciseID,
			&i.Weight,
			&i.Set,
			&i.Minute,
			&i.CreatedAt,
			&i.Subject,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchCategories = `-- name: FetchCategories :many
SELECT id, subject FROM exercise_category
`

func (q *Queries) FetchCategories(ctx context.Context) ([]ExerciseCategory, error) {
	rows, err := q.query(ctx, q.fetchCategoriesStmt, fetchCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseCategory
	for rows.Next() {
		var i ExerciseCategory
		if err := rows.Scan(&i.ID, &i.Subject); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchExerciseByCategoryId = `-- name: FetchExerciseByCategoryId :many
SELECT id, subject, category_id FROM exercise
WHERE category_id = ?
`

func (q *Queries) FetchExerciseByCategoryId(ctx context.Context, categoryID int64) ([]Exercise, error) {
	rows, err := q.query(ctx, q.fetchExerciseByCategoryIdStmt, fetchExerciseByCategoryId, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(&i.ID, &i.Subject, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchTodayExerciseByUserId = `-- name: FetchTodayExerciseByUserId :many
SELECT e.subject, COUNT(h.exercise_id) as count FROM health h
    INNER JOIN exercise e on h.exercise_id = e.id
    WHERE h.user_id = ? AND h.created_at BETWEEN ? AND ?
GROUP BY e.subject, h.exercise_id
`

type FetchTodayExerciseByUserIdParams struct {
	UserID      uuid.UUID
	CreatedAt   int64
	CreatedAt_2 int64
}

type FetchTodayExerciseByUserIdRow struct {
	Subject string
	Count   int64
}

func (q *Queries) FetchTodayExerciseByUserId(ctx context.Context, arg FetchTodayExerciseByUserIdParams) ([]FetchTodayExerciseByUserIdRow, error) {
	rows, err := q.query(ctx, q.fetchTodayExerciseByUserIdStmt, fetchTodayExerciseByUserId, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchTodayExerciseByUserIdRow
	for rows.Next() {
		var i FetchTodayExerciseByUserIdRow
		if err := rows.Scan(&i.Subject, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
